### ISSUE TITLE
taskwarrior-tui and totalactivetime

### ISSUE THREAD

**Issue by vanya-robertson** [tong/dot#1]
Hi, Tong!

Sorry for dropping in on you like this, but you're the only guy on GitHub with a file containing both the above strings. I have `on-modify.timetracking` from `kostajh/taskwarrior-time-tracking-hook` set up and `totalactivetime` set up in a review. Everything's fine and dandy, until I open it in `taskwarrior-tui`, when it gives me the value in seconds, not the `PT...H...M...S` format.

I have an estimate UDA set up and that shows its duration in the correct format, so the problem's `totalactivetime`-specific.

Have you encountered this problem?

Cheers, bub
Vanya

**Comment by tong** [comment]
Same problem here.
I can only speculate that taskwarrior-tui does not read the `duration` UDA correctly.

**Comment by vanya-robertson** [comment]
Good. I'm not alone, then.
